spring.application.name=snaply-backend
spring.config.import=optional:file:.env[.properties],optional:file:./.env[.properties],optional:file:../.env[.properties]
server.port=8080
app.frontend.url=${FRONTEND_URL:}
app.auth.dev-login-enabled=${AUTH_DEV_LOGIN_ENABLED:false}

#Supabase Pooler Connection
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}?sslmode=require
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis

spring.cache.type=redis

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=6000

# Mail (Google SMTP)
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Magic Link
magic-link.expiration-ms=600000

# JWT
jwt.secret=${JWT_SECRET:default_jwt_secret_key_change_in_production}
jwt.expiration=86400000

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO
